In [2]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\User\Downloads\customer_shopping_behavior.csv")

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
labels = ['Young Adult','Adult','Middle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [20]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [21]:
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [23]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [26]:
(df['discount_applied']== df['promo_code_used']).all()

np.True_

In [27]:
df=df.drop('promo_code_used',axis=1)

In [28]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [29]:
from sqlalchemy import create_engine
username = "postgres"
password = "Tox!cteddy1"
host = "localhost"
port = "5432"
database = "customer_behaviour"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace",index=False)

print(f"Data successfully loaded into table '{table_name}'in database '{database}'.")

Data successfully loaded into table 'customer'in database 'customer_behaviour'.